# Generated by Django 3.2.23 on 2023-12-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestinfo',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_no',
        ),
    ]
