# Generated by Django 3.2.23 on 2023-12-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0003_auto_20231211_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestinfo',
            name='phone_number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
